openapi: 3.0.1
info:
  title: title
  version: 1.0.0
paths: {}
components:
  parameters:
    pathParam1: 
      in: path
      name: param1
      schema:
        type: string
      required: true
    queryParam1:
      in: query
      name: param2
      schema:
        type: string
      required: false
  schemas:
    SampleArray:
      type: array
      items:
        $ref: '#/components/schemas/SampleResponse'
    SampleResponse:
      type: object
      properties:
        value:
          type: string