openapi: 3.0.1
info:
  title: title
  version: 1.0.0
paths:
  '/sample/point/{pathParam1}':
    get:
      tags:
        - api1
      operationId: getSamplePoint
      parameters:
        - $ref: './components.yml#/components/parameters/pathParam1'
        - $ref: './components.yml#/components/parameters/queryParam1'
      responses:
        '200':
          description: Pointの取得成功
          content:
            application/json: 
              schema:
                $ref: './components.yml#/components/schemas/SampleArray'
        '400':
          description: 不正なリクエストです。
        '401':
          description: 認証エラーです。
   